### ISSUE TITLE
git remote set-url origin https://github.com/MhdiTaheri/ProxyCollector.git error?

### ISSUE THREAD

**Issue by Epodonios** [MhdiTaheri/ProxyCollector#1]
git remote set-url origin https://github.com/MhdiTaheri/ProxyCollector.git error

**Comment by MhdiTaheri** [comment]
> git remote set-url origin https://github.com/MhdiTaheri/ProxyCollector.git error

in your .yml change this parameters i put in img :
1) user.email -> your github mail
2) user.name -> your github username 
3) for your error `https://github.com/MhdiTaheri/ProxyCollector.git` change this to your one like this: <br>**`https://github.com/{yourUserName}/{YourRepoName}.git`**
![error](https://github.com/MhdiTaheri/ProxyCollector/assets/151569179/02a05947-9deb-4c55-876c-e41079c3f6fe)
