### ISSUE TITLE
why bash commit dosent modify?

### ISSUE THREAD

**Issue by Epodonios** [MhdiTaheri/ProxyCollector#3]

**Comment by MhdiTaheri** [comment]
> _No description provided._

in your repo first
1) remove one of `.github/workflows`
2) after that go to this .yml file in this path `.github  /workflows/python_script.yml`
3) base on what i say in your first issue change the user.email and ...
4) know it should work

**Comment by MhdiTaheri** [comment]
> > _No description provided._
> 
> in your repo first
> 
> 1. remove one of `.github/workflows`
> 2. after that go to this .yml file in this path `.github  /workflows/python_script.yml`
> 3. base on what i say in your first issue change the user.email and ...
> 4. know it should work

The easier way is that first remove your repo and then fork this repo and just change the .yml file
