### ISSUE TITLE
unable to access 'https://github.com/Epodonios/ProxyCollector.git/': The requested URL returned error: 403 Error: Process completed with exit code 128

### ISSUE THREAD

**Issue by Epodonios** [MhdiTaheri/ProxyCollector#4]
unable to access 'https://github.com/Epodonios/ProxyCollector.git/': The requested URL returned error: 403
Error: Process completed with exit code 128

**Comment by MhdiTaheri** [comment]
go to your repo setting 
in actions tab 
General>Workflow permissions
put it on Read and write permissions and check Allow GitHub Actions to create and approve pull requests

**Comment by Epodonios** [comment]
Thank u sir🤍
